# Generated by Django 5.2.6 on 2025-10-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(help_text='Format: CountryCodeNumber, e.g., 2547XXXXXXXX', max_length=15)),
                ('account_reference', models.CharField(max_length=100)),
                ('transaction_desc', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mpesa Request',
                'verbose_name_plural': 'Mpesa Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MpesaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=10)),
                ('response_description', models.TextField()),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('customer_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mpesa.mpesarequest')),
            ],
            options={
                'verbose_name': 'Mpesa Response',
                'verbose_name_plural': 'Mpesa Responses',
                'ordering': ['-timestamp'],
            },
        ),
    ]
