# Generated by Django 5.2.6 on 2025-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_newsletter_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
